import type { Requirement, Column } from './types';

let codeCounter = { SCR: 8, FTR: 12, API: 5 };

export function generateCode(prefix: 'SCR' | 'FTR' | 'API'): string {
  codeCounter[prefix] += 1;
  return `${prefix}-${String(codeCounter[prefix]).padStart(4, '0')}`;
}

export const columns: Column[] = [
  { key: 'code', label: 'Code', labelJa: 'コード', width: 110, internalOnly: false, editable: false, clientEditable: false, type: 'code' },
  { key: 'category', label: 'Category', labelJa: 'カテゴリ', width: 120, internalOnly: false, editable: true, clientEditable: false, type: 'text' },
  { key: 'title_en', label: 'Title (EN)', labelJa: 'タイトル (英)', width: 220, internalOnly: false, editable: true, clientEditable: true, type: 'bilingual' },
  { key: 'title_ja', label: 'Title (JA)', labelJa: 'タイトル (日)', width: 220, internalOnly: false, editable: true, clientEditable: true, type: 'bilingual' },
  { key: 'description_en', label: 'Description (EN)', labelJa: '説明 (英)', width: 280, internalOnly: false, editable: true, clientEditable: true, type: 'bilingual' },
  { key: 'description_ja', label: 'Description (JA)', labelJa: '説明 (日)', width: 280, internalOnly: false, editable: true, clientEditable: true, type: 'bilingual' },
  { key: 'status', label: 'Status', labelJa: 'ステータス', width: 120, internalOnly: false, editable: true, clientEditable: false, type: 'status' },
  { key: 'priority', label: 'Priority', labelJa: '優先度', width: 100, internalOnly: false, editable: true, clientEditable: false, type: 'priority' },
  { key: 'assignee', label: 'Assignee', labelJa: '担当者', width: 140, internalOnly: true, editable: true, clientEditable: false, type: 'text' },
  { key: 'internalNotes_en', label: 'Internal Notes (EN)', labelJa: '内部メモ (英)', width: 240, internalOnly: true, editable: true, clientEditable: false, type: 'bilingual' },
  { key: 'internalNotes_ja', label: 'Internal Notes (JA)', labelJa: '内部メモ (日)', width: 240, internalOnly: true, editable: true, clientEditable: false, type: 'bilingual' },
  { key: 'techSpec_en', label: 'Tech Spec (EN)', labelJa: '技術仕様 (英)', width: 240, internalOnly: true, editable: true, clientEditable: false, type: 'bilingual' },
  { key: 'techSpec_ja', label: 'Tech Spec (JA)', labelJa: '技術仕様 (日)', width: 240, internalOnly: true, editable: true, clientEditable: false, type: 'bilingual' },
  { key: 'apiEndpoint', label: 'API Endpoint', labelJa: 'APIエンドポイント', width: 180, internalOnly: true, editable: true, clientEditable: false, type: 'text' },
  { key: 'updatedAt', label: 'Updated', labelJa: '更新日', width: 120, internalOnly: false, editable: false, clientEditable: false, type: 'date' },
];

export const initialRequirements: Requirement[] = [
  {
    id: '1',
    code: 'SCR-0001',
    category: 'UI/Screen',
    title: { en: 'Login Screen', ja: 'ログイン画面', syncStatus: 'synced', lastEditedLang: 'en' },
    description: { en: 'User authentication screen with email/password and SSO options', ja: 'メール/パスワードとSSOオプションを備えたユーザー認証画面', syncStatus: 'synced', lastEditedLang: 'en' },
    status: 'approved',
    priority: 'critical',
    assignee: 'Tanaka K.',
    internalNotes: { en: 'Use OAuth2.0 for SSO. Firebase Auth as backup.', ja: 'SSOにはOAuth2.0を使用。バックアップとしてFirebase Auth。', syncStatus: 'synced', lastEditedLang: 'en' },
    techSpec: { en: 'React + NextAuth.js, JWT tokens, refresh token rotation', ja: 'React + NextAuth.js、JWTトークン、リフレッシュトークンローテーション', syncStatus: 'synced', lastEditedLang: 'en' },
    apiEndpoint: 'POST /api/auth/login',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-15',
    updatedAt: '2026-04-10',
    attachments: 2,
    comments: 5,
  },
  {
    id: '2',
    code: 'SCR-0002',
    category: 'UI/Screen',
    title: { en: 'Dashboard Overview', ja: 'ダッシュボード概要', syncStatus: 'synced', lastEditedLang: 'ja' },
    description: { en: 'Main dashboard showing project summary, recent activity, and key metrics', ja: 'プロジェクト概要、最近のアクティビティ、主要指標を表示するメインダッシュボード', syncStatus: 'synced', lastEditedLang: 'ja' },
    status: 'in_progress',
    priority: 'high',
    assignee: 'Suzuki M.',
    internalNotes: { en: 'Use recharts for visualization. Cache dashboard data.', ja: '可視化にはrechartsを使用。ダッシュボードデータをキャッシュ。', syncStatus: 'synced', lastEditedLang: 'en' },
    techSpec: { en: 'Server-side rendering for initial load, WebSocket for live updates', ja: '初回読み込みにサーバーサイドレンダリング、ライブ更新にWebSocket', syncStatus: 'synced', lastEditedLang: 'en' },
    apiEndpoint: 'GET /api/dashboard/summary',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-16',
    updatedAt: '2026-04-12',
    attachments: 3,
    comments: 8,
  },
  {
    id: '3',
    code: 'FTR-0001',
    category: 'Feature',
    title: { en: 'Bilingual Input System', ja: 'バイリンガル入力システム', syncStatus: 'pending', lastEditedLang: 'en' },
    description: { en: 'Bidirectional translation engine supporting EN/JA with context-aware AI', ja: 'コンテキスト対応AIによるEN/JA対応双方向翻訳エンジン', syncStatus: 'pending', lastEditedLang: 'en' },
    status: 'in_progress',
    priority: 'critical',
    assignee: 'Villanueva R.',
    internalNotes: { en: 'Phase 1: Basic translation. Phase 2: Context-aware AI using project glossary.', ja: 'フェーズ1：基本翻訳。フェーズ2：プロジェクト用語集を使用したコンテキスト対応AI。', syncStatus: 'pending', lastEditedLang: 'en' },
    techSpec: { en: 'Translation microservice, glossary DB, queue-based async processing', ja: '翻訳マイクロサービス、用語集DB、キューベースの非同期処理', syncStatus: 'pending', lastEditedLang: 'en' },
    apiEndpoint: 'POST /api/translate',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-18',
    updatedAt: '2026-04-15',
    attachments: 1,
    comments: 12,
  },
  {
    id: '4',
    code: 'FTR-0002',
    category: 'Feature',
    title: { en: 'Dual-Book View System', ja: 'デュアルブック表示システム', syncStatus: 'synced', lastEditedLang: 'en' },
    description: { en: 'Synchronized internal/client view system with configurable column visibility', ja: '設定可能なカラム表示を備えた内部/クライアントビュー同期システム', syncStatus: 'synced', lastEditedLang: 'en' },
    status: 'review',
    priority: 'high',
    assignee: 'Tanaka K.',
    internalNotes: { en: 'Column-level ACL required. Client view must strip all internal fields at API level.', ja: 'カラムレベルのACLが必要。クライアントビューはAPIレベルで全内部フィールドを除去する必要あり。', syncStatus: 'synced', lastEditedLang: 'en' },
    techSpec: { en: 'Middleware-based field filtering, role-based column projection', ja: 'ミドルウェアベースのフィールドフィルタリング、ロールベースのカラム投影', syncStatus: 'synced', lastEditedLang: 'en' },
    apiEndpoint: 'GET /api/requirements?view=client',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-20',
    updatedAt: '2026-04-14',
    attachments: 0,
    comments: 6,
  },
  {
    id: '5',
    code: 'FTR-0003',
    category: 'Feature',
    title: { en: 'Unique Code Generator', ja: '一意コード生成機能', syncStatus: 'synced', lastEditedLang: 'ja' },
    description: { en: 'Automatic immutable unique ID assignment for screens and features', ja: '画面と機能への自動的な不変一意ID割り当て', syncStatus: 'synced', lastEditedLang: 'ja' },
    status: 'completed',
    priority: 'medium',
    assignee: 'Suzuki M.',
    internalNotes: { en: 'Prefix-based: SCR for screens, FTR for features, API for endpoints.', ja: 'プレフィックスベース：画面はSCR、機能はFTR、エンドポイントはAPI。', syncStatus: 'synced', lastEditedLang: 'ja' },
    techSpec: { en: 'Database sequence + prefix mapping, immutable after creation', ja: 'データベースシーケンス + プレフィックスマッピング、作成後は不変', syncStatus: 'synced', lastEditedLang: 'ja' },
    apiEndpoint: 'POST /api/codes/generate',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-22',
    updatedAt: '2026-04-08',
    attachments: 0,
    comments: 3,
  },
  {
    id: '6',
    code: 'SCR-0003',
    category: 'UI/Screen',
    title: { en: 'User Management Panel', ja: 'ユーザー管理パネル', syncStatus: 'translating', lastEditedLang: 'en' },
    description: { en: 'Admin panel for managing users, roles, and permissions', ja: 'ユーザー、ロール、権限を管理する管理パネル', syncStatus: 'translating', lastEditedLang: 'en' },
    status: 'draft',
    priority: 'medium',
    assignee: 'Villanueva R.',
    internalNotes: { en: 'Only admin role should see this screen. Audit log required.', ja: '管理者ロールのみこの画面を表示可能。監査ログが必要。', syncStatus: 'translating', lastEditedLang: 'en' },
    techSpec: { en: 'RBAC with Casbin, admin-only route guard', ja: 'CasbinによるRBAC、管理者専用ルートガード', syncStatus: 'translating', lastEditedLang: 'en' },
    apiEndpoint: 'GET /api/admin/users',
    clientVisible: false,
    clientEditable: false,
    createdAt: '2026-03-25',
    updatedAt: '2026-04-16',
    attachments: 1,
    comments: 2,
  },
  {
    id: '7',
    code: 'FTR-0004',
    category: 'Feature',
    title: { en: 'PDF/CSV Export Engine', ja: 'PDF/CSVエクスポートエンジン', syncStatus: 'synced', lastEditedLang: 'en' },
    description: { en: 'Export filtered views to PDF and CSV with bilingual content support', ja: 'バイリンガルコンテンツ対応でフィルタリングされたビューをPDFとCSVにエクスポート', syncStatus: 'synced', lastEditedLang: 'en' },
    status: 'draft',
    priority: 'low',
    assignee: 'Tanaka K.',
    internalNotes: { en: 'Use Puppeteer for PDF, papaparse for CSV. Queue heavy exports.', ja: 'PDFにはPuppeteer、CSVにはpapaparseを使用。重いエクスポートはキューに入れる。', syncStatus: 'synced', lastEditedLang: 'en' },
    techSpec: { en: 'Puppeteer headless rendering, streaming CSV generation', ja: 'Puppeteerヘッドレスレンダリング、ストリーミングCSV生成', syncStatus: 'synced', lastEditedLang: 'en' },
    apiEndpoint: 'POST /api/export',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-04-01',
    updatedAt: '2026-04-11',
    attachments: 0,
    comments: 1,
  },
  {
    id: '8',
    code: 'API-0001',
    category: 'API',
    title: { en: 'Authentication API', ja: '認証API', syncStatus: 'synced', lastEditedLang: 'en' },
    description: { en: 'REST API endpoints for user authentication, session management, and token refresh', ja: 'ユーザー認証、セッション管理、トークンリフレッシュ用のREST APIエンドポイント', syncStatus: 'synced', lastEditedLang: 'en' },
    status: 'approved',
    priority: 'critical',
    assignee: 'Villanueva R.',
    internalNotes: { en: 'Rate limiting: 5 attempts per minute. Lockout after 10 failures.', ja: 'レート制限：1分あたり5回まで。10回失敗でロックアウト。', syncStatus: 'synced', lastEditedLang: 'en' },
    techSpec: { en: 'Express.js middleware, bcrypt hashing, Redis session store', ja: 'Express.jsミドルウェア、bcryptハッシュ、Redisセッションストア', syncStatus: 'synced', lastEditedLang: 'en' },
    apiEndpoint: 'POST /api/auth/*',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-16',
    updatedAt: '2026-04-09',
    attachments: 1,
    comments: 7,
  },
  {
    id: '9',
    code: 'SCR-0004',
    category: 'UI/Screen',
    title: { en: 'Client Portal Landing', ja: 'クライアントポータルランディング', syncStatus: 'synced', lastEditedLang: 'ja' },
    description: { en: 'Restricted landing page for client/guest users with filtered project view', ja: 'フィルタリングされたプロジェクトビューを持つクライアント/ゲストユーザー向けの制限付きランディングページ', syncStatus: 'synced', lastEditedLang: 'ja' },
    status: 'review',
    priority: 'high',
    assignee: 'Suzuki M.',
    internalNotes: { en: 'Must completely hide internal columns. Use separate API projection.', ja: '内部カラムを完全に非表示にする必要あり。別のAPIプロジェクションを使用。', syncStatus: 'synced', lastEditedLang: 'ja' },
    techSpec: { en: 'Next.js middleware for role-based routing, field-level security', ja: 'ロールベースルーティング用Next.jsミドルウェア、フィールドレベルセキュリティ', syncStatus: 'synced', lastEditedLang: 'ja' },
    apiEndpoint: 'GET /api/portal/overview',
    clientVisible: true,
    clientEditable: false,
    createdAt: '2026-03-28',
    updatedAt: '2026-04-13',
    attachments: 2,
    comments: 4,
  },
  {
    id: '10',
    code: 'FTR-0005',
    category: 'Feature',
    title: { en: 'Real-time Collaboration', ja: 'リアルタイムコラボレーション', syncStatus: 'conflict', lastEditedLang: 'en' },
    description: { en: 'WebSocket-based live editing with conflict resolution and presence indicators', ja: 'コンフリクト解決とプレゼンスインジケーターを備えたWebSocketベースのライブ編集', syncStatus: 'conflict', lastEditedLang: 'en' },
    status: 'draft',
    priority: 'medium',
    assignee: 'Tanaka K.',
    internalNotes: { en: 'CRDT for conflict resolution. Consider Y.js or Automerge.', ja: 'コンフリクト解決にCRDT。Y.jsまたはAutomergeを検討。', syncStatus: 'conflict', lastEditedLang: 'en' },
    techSpec: { en: 'WebSocket (Socket.io), Y.js CRDT, Redis pub/sub for scaling', ja: 'WebSocket (Socket.io)、Y.js CRDT、スケーリング用Redis pub/sub', syncStatus: 'conflict', lastEditedLang: 'en' },
    apiEndpoint: 'WS /api/ws/collaborate',
    clientVisible: false,
    clientEditable: false,
    createdAt: '2026-04-05',
    updatedAt: '2026-04-17',
    attachments: 0,
    comments: 9,
  },
];

export const mockTranslations: Record<string, string> = {
  'Login Screen': 'ログイン画面',
  'Dashboard Overview': 'ダッシュボード概要',
  'Bilingual Input System': 'バイリンガル入力システム',
  'Real-time Collaboration': 'リアルタイムコラボレーション',
  'User authentication screen': 'ユーザー認証画面',
};
